### ISSUE TITLE
Why can't I apply changes to the dock setting?

### ISSUE THREAD

**Issue by SiriusGS** [w0lfschild/cDock2#26]
The theme works fine. But when I try to change icon size or anything under Dock settings, I cannot apply. Why is this?

**Comment by w0lfschild** [comment]
Your Dock plist is probably locked or having a problem saving/updating.

Deleting ~/Library/Preferences/com.apple.dock.plist and logging out and back in should fix the issue.

**Comment by grkka** [comment]
For the only thing was used CDock in Yosemite to put the transparent dock, but at El Capitan can not. Why?

**Comment by SiriusGS** [comment]
Thanks for the reply. But it still does not work. When I try to enter some numbers to change size and spacers and click on "apply ", nothing happens.

**Comment by w0lfschild** [comment]
What version of OS X?

**Comment by SiriusGS** [comment]
El Capitan 10.11.3

**Comment by ManOnHorse** [comment]
I have similar problems:
On a MBP OSX 10.11.3 I have cDock2 10.3 working without a problem (after disableling SIP)
Yesterday i upgraded another MBP to OSx 10.11.3 and installed cDock2 10.4. It doesn't work.
Also cDock2 10.3 did work on this machine.  Strange. Any insight?

**Comment by ManOnHorse** [comment]
additional information:
cDock2 10.3 and 10.4 working on MacBookPro11,3
cDock2 10.3 and 10.4 not working on recently upgraded MacBookPro10,1

**Comment by Moscarda** [comment]
Is this issue referring to cDcck 1 or 2 ? BecauseI know how to create themes in version 1, but don't see it on 2. Is it just an El Capitan issue?  Because I DO have SIP protection turned off.

Not only can I not create new themes in cDock 2, but many of the features there are buttons and checkboxes for are not applied when clicking apply and restarting the dock.

**Comment by w0lfschild** [comment]
@Moscarda 

There are a couple reasons why cDock may not be working. Most are discussed here: https://github.com/w0lfschild/cDock2/issues/2

I can however say that it for sure does work on El Capitan because I'm using it just fine right now on the latest Beta build.

**Comment by kylebrowning** [comment]
How do you install beta?

**Comment by w0lfschild** [comment]
There is no beta, at least currently.

**Comment by Eli-Carpenter** [comment]
when I try to apply themes on my MacBook 4,1 on OS X Yosemite 10.10 with cDock 2 and restart the dock it still has the OS X Yosemite dock
I am trying to make a dock that looks like the iOS 11 iPad dock
