### ISSUE TITLE
I accidentally used cDock for macOS Big Sur on Mojave 

### ISSUE THREAD

**Issue by ghost** [w0lfschild/cDock2#297]
And it messed up my dock, then i downloaded the correct version of cDock for Mojave and applied the default style, since then every time i reboot the dock relaunches it self non stop, until i open cDock and press restart dock. Is there any possible fix to this, like reverting completely to the default Mojave setting?

**Comment by w0lfschild** [comment]
Deleting these files should fix it

```
/Library/Application Support/MacEnhance/Plugins/_DockKit.bundle
/Library/Application Support/MacEnhance/Plugins/cDock.bundle
```

**Comment by ghost** [comment]
I only see cDock.bundle, i tried deleting it and rebooting, but the problem persists. The dock appeared with a counter on the trashcan (displaying number of deleted files) this time after rebooting. And now the dock crashes randomly. Even after restarting the dock with cDock.

**Comment by w0lfschild** [comment]
Maybe you're experiencing a different issue?

Do you have other plugins installed? 

You can share a zip of your crash logs from here: `~/Library/Logs/DiagnosticReports/`

**Comment by ghost** [comment]
I may have had an older version of cDock, i'm not sure. But no other plugins. (i seem to be unable to attach files in my browser) so here is a link to the two latest crashes: https://www.noob.software/archive.zip

**Comment by w0lfschild** [comment]
Never seen that crash before, seems like maybe the Paddle framework is failing to load from inside the bundle.

What version of cDock are you using?

**Comment by ghost** [comment]
cDock v3.1.2
Helper v2.0.1
Bundle v3.4.0

**Comment by ghost** [comment]
There is also another type of error

Application Specific Information:
dyld3 mode
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<Dock.CartoucheBackdropLayerController 0x7fdc255224a0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _materialLayer.'
terminating with uncaught exception of type NSException
abort() called

**Comment by ghost** [comment]
Is this fixed in the next update of cDock or what is the solution?

**Comment by w0lfschild** [comment]
Any issue you're having with v3 won't be fixed. 
Your options are trying some older versions from https://github.com/w0lfschild/app_updates or try out v4 of cDock.

**Comment by ghost** [comment]
I've tried deleting the files you recommended that is cDock.bundle, _DockKit.bundle was not present. The problem started when i used v4, on mojave so that probably won't solve my problem, although i can try it if you recommend it. I do think since i paid for both versions of the application, that i should get a little help. Is there anything you can recommend? There must be a way to undo/deactivate what cdock does?

**Comment by w0lfschild** [comment]
Did you have it working beforehand?
v4 definitely works on 10.14 but so should v3

Try deleting everything relating to cDock and MacForge if you have it installed

```
/Applications/MacForge.app
/Applications/cDock.app

/$HOME/Library/Application Support/cDock

/Library/Application Support/MacEnhance

/Library/LaunchDaemons/com.macenhance.cDock.Injector.plist
/Library/PrivilegedHelperTools/com.macenhance.cDock.Injector

/Library/LaunchDaemons/com.macenhance.MacForge.Injector.plist
/Library/PrivilegedHelperTools/com.macenhance.MacForge.Injector
```

Then restart and re-install cDock.
